#!/usr/bin/env bash
# ==============================================================================
# MAYOTIX OS — ISO Builder
# File: scripts/build-iso.sh
# Mode: 0755
# Description: Builds a bootable MAYOTIX OS Live ISO using Fedora's
#              livemedia-creator with a fully hardened Kickstart configuration.
#              Run on a Fedora system with sudo privileges.
# ==============================================================================

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

ISO_OUTPUT_DIR="${REPO_ROOT}/build"
ISO_NAME="mayotix-os-5.0-alpha-x86_64.iso"
KS_FILE="${REPO_ROOT}/installer/kickstart/mayotix-iso.ks"
LORAX_TMPDIR="/var/tmp/mayotix-iso-build"

echo -e "${BLUE}${BOLD}"
echo "=============================================================================="
echo "          MAYOTIX OS — Bootable Live ISO Builder                              "
echo "=============================================================================="
echo -e "${NC}"

# --------------------------------------------------------------------------
# Step 0: Check prerequisites
# --------------------------------------------------------------------------
echo -e "${BLUE}[INFO]${NC} Checking prerequisites..."

if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}[ERROR]${NC} This script must be run as root (sudo)."
    echo "  Usage: sudo ./scripts/build-iso.sh"
    exit 1
fi

# Install required tools
REQUIRED_PKGS=(lorax livecd-tools anaconda pykickstart)
MISSING_PKGS=()

for pkg in "${REQUIRED_PKGS[@]}"; do
    if ! rpm -q "$pkg" &>/dev/null; then
        MISSING_PKGS+=("$pkg")
    fi
done

if [[ ${#MISSING_PKGS[@]} -gt 0 ]]; then
    echo -e "${YELLOW}[WARN]${NC} Installing missing packages: ${MISSING_PKGS[*]}"
    dnf install -y "${MISSING_PKGS[@]}"
fi

echo -e "${GREEN}[✓]${NC} All prerequisites satisfied."

# --------------------------------------------------------------------------
# Step 1: Generate the complete Kickstart
# --------------------------------------------------------------------------
echo -e "${BLUE}[INFO]${NC} Generating complete MAYOTIX OS Kickstart file..."

cat > "$KS_FILE" << 'KICKSTART_EOF'
# ==============================================================================
# MAYOTIX OS — Complete Live ISO Kickstart
# Auto-generated by scripts/build-iso.sh
# ==============================================================================

# Installation Mode
version=F40
text
reboot

# Keyboard and Localization
keyboard --vckeymap=us --xlayouts='us'
lang en_US.UTF-8
timezone UTC --utc

# Network Configuration
network --bootproto=dhcp --device=link --activate --onboot=on --hostname=mayotix

# SELinux and Firewall
selinux --enforcing
firewall --enabled --ssh

# Authentication
rootpw --lock
user --name=mayotix --groups=wheel --plaintext --password=mayotix --gecos="MAYOTIX OS User"

# Partitioning (UEFI + LUKS2 + Btrfs)
zerombr
clearpart --all --initlabel

part /boot/efi --fstype="efi" --size=600 --fsoptions="umask=0077,shortname=winnt"
part /boot --fstype="ext4" --size=1024 --label=MAYOTIX_BOOT
part btrfs.mayotix --fstype="btrfs" --size=30000 --grow --encrypted --luks-version=luks2 --cipher=aes-xts-plain64 --pbkdf=argon2id

btrfs none --label=MAYOTIX_SYS btrfs.mayotix
btrfs / --subvol --name=root MAYOTIX_SYS
btrfs /home --subvol --name=home MAYOTIX_SYS
btrfs /var/log --subvol --name=var_log MAYOTIX_SYS
btrfs /var/cache --subvol --name=var_cache MAYOTIX_SYS

# Package Manifest
%packages
@core
@standard
@hardware-support
kernel
grub2-efi-x64
shim-x64
btrfs-progs
cryptsetup
clevis
clevis-luks

# Security & Hardening
selinux-policy-targeted
nftables
audit
bubblewrap
flatpak
tpm2-tools
wireguard-tools

# Networking
systemd-resolved
iproute

# Python (for daemon & tools)
python3
python3-pip

# Desktop Environment
@base-x
sway
foot
waybar
wofi
mako
grim
slurp
wl-clipboard
xdg-utils
desktop-file-utils

# Development & Analysis Tools
git
tcpdump
nmap-ncat
strace
ltrace
procps-ng
inotify-tools
%end

# Post-Installation: Deploy MAYOTIX OS
%post --log=/root/mayotix-post-install.log
echo "[INFO] ===== MAYOTIX OS Post-Installation Deployment ====="

# ---------- Clone MAYOTIX OS Repository ----------
MAYOTIX_SRC="/opt/mayotix-os"
git clone https://github.com/ameyarawat/mayotix-os.git "$MAYOTIX_SRC" || true

# ---------- Install CLI ----------
cp "$MAYOTIX_SRC/cli/mayotix" /usr/local/bin/mayotix
chmod +x /usr/local/bin/mayotix

# ---------- Install Daemon ----------
cp "$MAYOTIX_SRC/daemon/mayotix-daemon.py" /usr/local/sbin/mayotix-daemon
chmod +x /usr/local/sbin/mayotix-daemon

# ---------- Install Systemd Service ----------
cp "$MAYOTIX_SRC/system/mayotix-daemon.service" /etc/systemd/system/
systemctl enable mayotix-daemon.service

# ---------- Deploy Security Configs ----------
# Sysctl hardening
cat > /etc/sysctl.d/99-mayotix-hardened.conf << 'SYSCTL'
fs.suid_dumpable = 0
kernel.randomize_va_space = 2
kernel.kptr_restrict = 2
kernel.dmesg_restrict = 1
kernel.unprivileged_bpf_disabled = 1
kernel.yama.ptrace_scope = 2
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv6.conf.all.disable_ipv6 = 0
SYSCTL

# Network configs
mkdir -p /etc/systemd/resolved.conf.d
cp -r "$MAYOTIX_SRC/config/network/"* /etc/systemd/resolved.conf.d/ 2>/dev/null || true

# Firewall configs
cp -r "$MAYOTIX_SRC/config/firewall/"* /etc/nftables/ 2>/dev/null || true

# ---------- Install Desktop Apps ----------
mkdir -p /usr/share/mayotix/pentest
mkdir -p /usr/share/mayotix/installer
mkdir -p /usr/share/mayotix/gaming
cp -r "$MAYOTIX_SRC/desktop/pentest/"* /usr/share/mayotix/pentest/ 2>/dev/null || true
cp -r "$MAYOTIX_SRC/desktop/installer/"* /usr/share/mayotix/installer/ 2>/dev/null || true
cp -r "$MAYOTIX_SRC/desktop/gaming/"* /usr/share/mayotix/gaming/ 2>/dev/null || true
cp "$MAYOTIX_SRC/desktop/applications/"*.desktop /usr/share/applications/ 2>/dev/null || true

# ---------- Install Pentest Tools ----------
mkdir -p /usr/local/share/mayotix/pentest
cp "$MAYOTIX_SRC/tests/pentest/"* /usr/local/share/mayotix/pentest/ 2>/dev/null || true
chmod +x /usr/local/share/mayotix/pentest/*.sh /usr/local/share/mayotix/pentest/*.py 2>/dev/null || true

# ---------- Install Installer Scripts ----------
mkdir -p /usr/local/sbin
cp "$MAYOTIX_SRC/installer/"*.sh /usr/local/sbin/ 2>/dev/null || true
chmod +x /usr/local/sbin/mayotix-installer.sh /usr/local/sbin/partition-validator.sh /usr/local/sbin/luks2-setup.sh 2>/dev/null || true

# ---------- SELinux Policies ----------
cp "$MAYOTIX_SRC/security/selinux/"*.te "$MAYOTIX_SRC/security/selinux/"*.fc /usr/share/selinux/packages/ 2>/dev/null || true

# ---------- Enable SELinux Relabeling ----------
touch /.autorelabel

# ---------- Enable Services ----------
systemctl enable auditd.service
systemctl enable nftables.service
systemctl enable systemd-resolved.service

# ---------- MAYOTIX MOTD Banner ----------
cat > /etc/motd << 'MOTD'

  ╔══════════════════════════════════════════════════════════════╗
  ║                    MAYOTIX OS v5.0-alpha                    ║
  ║           Security-Hardened Linux Distribution              ║
  ║                                                              ║
  ║  SELinux: Enforcing  |  Firewall: nftables (Fail-Closed)   ║
  ║  DNS: DoT Encrypted  |  VPN: WireGuard Ready              ║
  ║  Encryption: LUKS2 Argon2id  |  FS: Btrfs Subvolumes      ║
  ║                                                              ║
  ║  Run 'mayotix status --json' for system health             ║
  ║  Run 'mayotix --help' for all available commands           ║
  ╚══════════════════════════════════════════════════════════════╝

MOTD

echo "[✓] MAYOTIX OS Post-Installation Complete."
%end
KICKSTART_EOF

echo -e "${GREEN}[✓]${NC} Kickstart file generated: ${KS_FILE}"

# --------------------------------------------------------------------------
# Step 2: Validate Kickstart
# --------------------------------------------------------------------------
echo -e "${BLUE}[INFO]${NC} Validating Kickstart syntax..."
if command -v ksvalidator &>/dev/null; then
    ksvalidator "$KS_FILE" && echo -e "${GREEN}[✓]${NC} Kickstart syntax valid." || echo -e "${YELLOW}[WARN]${NC} Kickstart validation warnings (non-fatal)."
else
    echo -e "${YELLOW}[WARN]${NC} ksvalidator not found, skipping validation."
fi

# --------------------------------------------------------------------------
# Step 3: Build the ISO
# --------------------------------------------------------------------------
echo -e "${BLUE}[INFO]${NC} Building MAYOTIX OS Live ISO..."
echo -e "${YELLOW}[WARN]${NC} This process takes 15-30 minutes and requires ~10GB free disk space."

mkdir -p "$ISO_OUTPUT_DIR"
mkdir -p "$LORAX_TMPDIR"

livemedia-creator \
    --ks="$KS_FILE" \
    --no-virt \
    --resultdir="$ISO_OUTPUT_DIR" \
    --project="MAYOTIX OS" \
    --releasever=40 \
    --iso-only \
    --iso-name="$ISO_NAME" \
    --tmp="$LORAX_TMPDIR" \
    --logfile="$ISO_OUTPUT_DIR/build.log"

# --------------------------------------------------------------------------
# Step 4: Done
# --------------------------------------------------------------------------
if [[ -f "${ISO_OUTPUT_DIR}/${ISO_NAME}" ]]; then
    ISO_SIZE=$(du -h "${ISO_OUTPUT_DIR}/${ISO_NAME}" | cut -f1)
    echo ""
    echo -e "${GREEN}${BOLD}=============================================================================="
    echo "  MAYOTIX OS ISO Build Complete!"
    echo "=============================================================================="
    echo -e "${NC}"
    echo -e "  ISO File : ${BOLD}${ISO_OUTPUT_DIR}/${ISO_NAME}${NC}"
    echo -e "  Size     : ${ISO_SIZE}"
    echo ""
    echo "  To use:"
    echo "    1. Copy the ISO to your host machine"
    echo "    2. Create a new VM in VirtualBox/VMware (4GB RAM, 40GB disk, EFI boot)"
    echo "    3. Mount the ISO and boot from it"
    echo "    4. Login: username=mayotix password=mayotix"
    echo ""
else
    echo -e "${RED}[ERROR]${NC} ISO build failed. Check: ${ISO_OUTPUT_DIR}/build.log"
    exit 1
fi
